### ISSUE TITLE
Its not workin now

### ISSUE THREAD

**Issue by Umeshkanase17** [vikram25897/flutter_cached_video_player#105]
Its not working now 
 

Workaround for now:

```
 cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump
```

_Originally posted by @milan-ciganovic in https://github.com/vikram25897/flutter_cached_video_player/issues/64#issuecomment-1514809365_
