### ISSUE TITLE
Deprecated namespace declaration causing build failures

### ISSUE THREAD

**Issue by Bus42** [vikram25897/flutter_cached_video_player#99]
I am getting the following error when trying to build. I think that cached_video_player needs a little updating.

```cli
Incorrect package="com.lazyarts.vikram.cached_video_player" found in source AndroidManifest.xml: C:\Users\gbrew\AppData\Local\Pub\Cache\hosted\pub.dev\cached_video_player-2.0.4\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.lazyarts.vikram.cached_video_player" from the source AndroidManifest.xml: C:\Users\gbrew\AppData\Local\Pub\Cache\hosted\pub.dev\cached_video_player-2.0.4\android\src\main\AndroidManifest.xml.

FAILURE: Build failed with an exception.
```

**Comment by Lazizbek97** [comment]
any news?

**Comment by wildsurfer** [comment]
+1

**Comment by wildsurfer** [comment]
Solution seems to be here: https://github.com/vikram25897/flutter_cached_video_player/pull/81

**Comment by AkhileshGahlot** [comment]
As a temporary fix this resolved my issue:

> add this
> android {
> namespace = "com.lazyarts.vikram.cached_video_player"
> ....
> }
> in
> External Libraries/Flutter Plugins/cached_video_player-2.0.4/android/build.gradle

**Comment by trunghieuvn** [comment]
I forked and fixed here
I used flutter 3.29.

```
dependency_overrides:
    cached_video_player: # ^2.0.4
        git:
            url: https://github.com/trunghieuvn/flutter_cached_video_player
            ref: 3f343d3
```
